-- Chocolate Milk Dark for lualine (LazyVim's status line). Generated by tools/build.py; do not edit.
return {
  normal = { a = { fg = "#4A382F", bg = "#E0A86E", gui = "bold" }, b = { fg = "#F2E7DE", bg = "#625048" }, c = { fg = "#B7AAA1", bg = "#3F2F28" } },
  insert = { a = { fg = "#4A382F", bg = "#B0CA85", gui = "bold" }, b = { fg = "#F2E7DE", bg = "#625048" }, c = { fg = "#B7AAA1", bg = "#3F2F28" } },
  visual = { a = { fg = "#4A382F", bg = "#CCA2CA", gui = "bold" }, b = { fg = "#F2E7DE", bg = "#625048" }, c = { fg = "#B7AAA1", bg = "#3F2F28" } },
  replace = { a = { fg = "#4A382F", bg = "#F4887D", gui = "bold" }, b = { fg = "#F2E7DE", bg = "#625048" }, c = { fg = "#B7AAA1", bg = "#3F2F28" } },
  command = { a = { fg = "#4A382F", bg = "#F1D180", gui = "bold" }, b = { fg = "#F2E7DE", bg = "#625048" }, c = { fg = "#B7AAA1", bg = "#3F2F28" } },
  terminal = { a = { fg = "#4A382F", bg = "#90C8B0", gui = "bold" }, b = { fg = "#F2E7DE", bg = "#625048" }, c = { fg = "#B7AAA1", bg = "#3F2F28" } },
  inactive = { a = { fg = "#B3A097", bg = "#3F2F28" }, b = { fg = "#B3A097", bg = "#3F2F28" }, c = { fg = "#B3A097", bg = "#3F2F28" } },
}
