-- Chocolate Milk Light for lualine (LazyVim's status line). Generated by tools/build.py; do not edit.
return {
  normal = { a = { fg = "#F2ECE7", bg = "#8E5B34", gui = "bold" }, b = { fg = "#46322B", bg = "#DAD2CD" }, c = { fg = "#6D615B", bg = "#E8DED7" } },
  insert = { a = { fg = "#F2ECE7", bg = "#536F30", gui = "bold" }, b = { fg = "#46322B", bg = "#DAD2CD" }, c = { fg = "#6D615B", bg = "#E8DED7" } },
  visual = { a = { fg = "#F2ECE7", bg = "#87528A", gui = "bold" }, b = { fg = "#46322B", bg = "#DAD2CD" }, c = { fg = "#6D615B", bg = "#E8DED7" } },
  replace = { a = { fg = "#F2ECE7", bg = "#AC4343", gui = "bold" }, b = { fg = "#46322B", bg = "#DAD2CD" }, c = { fg = "#6D615B", bg = "#E8DED7" } },
  command = { a = { fg = "#F2ECE7", bg = "#7B6415", gui = "bold" }, b = { fg = "#46322B", bg = "#DAD2CD" }, c = { fg = "#6D615B", bg = "#E8DED7" } },
  terminal = { a = { fg = "#F2ECE7", bg = "#2D7165", gui = "bold" }, b = { fg = "#46322B", bg = "#DAD2CD" }, c = { fg = "#6D615B", bg = "#E8DED7" } },
  inactive = { a = { fg = "#7C6C63", bg = "#E8DED7" }, b = { fg = "#7C6C63", bg = "#E8DED7" }, c = { fg = "#7C6C63", bg = "#E8DED7" } },
}
