-- Cocoa Copper Dark for lualine (LazyVim's status line). Generated by tools/build.py; do not edit.
return {
  normal = { a = { fg = "#3A2B2A", bg = "#E58076", gui = "bold" }, b = { fg = "#F1E5DE", bg = "#544543" }, c = { fg = "#B1A49F", bg = "#2D2221" } },
  insert = { a = { fg = "#3A2B2A", bg = "#A3C164", gui = "bold" }, b = { fg = "#F1E5DE", bg = "#544543" }, c = { fg = "#B1A49F", bg = "#2D2221" } },
  visual = { a = { fg = "#3A2B2A", bg = "#D79AEE", gui = "bold" }, b = { fg = "#F1E5DE", bg = "#544543" }, c = { fg = "#B1A49F", bg = "#2D2221" } },
  replace = { a = { fg = "#3A2B2A", bg = "#F46F68", gui = "bold" }, b = { fg = "#F1E5DE", bg = "#544543" }, c = { fg = "#B1A49F", bg = "#2D2221" } },
  command = { a = { fg = "#3A2B2A", bg = "#FECE69", gui = "bold" }, b = { fg = "#F1E5DE", bg = "#544543" }, c = { fg = "#B1A49F", bg = "#2D2221" } },
  terminal = { a = { fg = "#3A2B2A", bg = "#5AD2B8", gui = "bold" }, b = { fg = "#F1E5DE", bg = "#544543" }, c = { fg = "#B1A49F", bg = "#2D2221" } },
  inactive = { a = { fg = "#A39088", bg = "#2D2221" }, b = { fg = "#A39088", bg = "#2D2221" }, c = { fg = "#A39088", bg = "#2D2221" } },
}
