-- Cocoa Rose Dark for lualine (LazyVim's status line). Generated by tools/build.py; do not edit.
return {
  normal = { a = { fg = "#382A2D", bg = "#ED8888", gui = "bold" }, b = { fg = "#F0E3DF", bg = "#524446" }, c = { fg = "#B0A2A1", bg = "#2C2124" } },
  insert = { a = { fg = "#382A2D", bg = "#A6C062", gui = "bold" }, b = { fg = "#F0E3DF", bg = "#524446" }, c = { fg = "#B0A2A1", bg = "#2C2124" } },
  visual = { a = { fg = "#382A2D", bg = "#E093E1", gui = "bold" }, b = { fg = "#F0E3DF", bg = "#524446" }, c = { fg = "#B0A2A1", bg = "#2C2124" } },
  replace = { a = { fg = "#382A2D", bg = "#F66C75", gui = "bold" }, b = { fg = "#F0E3DF", bg = "#524446" }, c = { fg = "#B0A2A1", bg = "#2C2124" } },
  command = { a = { fg = "#382A2D", bg = "#FACB62", gui = "bold" }, b = { fg = "#F0E3DF", bg = "#524446" }, c = { fg = "#B0A2A1", bg = "#2C2124" } },
  terminal = { a = { fg = "#382A2D", bg = "#53D2BD", gui = "bold" }, b = { fg = "#F0E3DF", bg = "#524446" }, c = { fg = "#B0A2A1", bg = "#2C2124" } },
  inactive = { a = { fg = "#A08A8A", bg = "#2C2124" }, b = { fg = "#A08A8A", bg = "#2C2124" }, c = { fg = "#A08A8A", bg = "#2C2124" } },
}
