-- Cocoa Copper Light for lualine (LazyVim's status line). Generated by tools/build.py; do not edit.
return {
  normal = { a = { fg = "#F4ECE6", bg = "#892B32", gui = "bold" }, b = { fg = "#3A2B2A", bg = "#DAD1CC" }, c = { fg = "#6C615F", bg = "#EADFD7" } },
  insert = { a = { fg = "#F4ECE6", bg = "#476517", gui = "bold" }, b = { fg = "#3A2B2A", bg = "#DAD1CC" }, c = { fg = "#6C615F", bg = "#EADFD7" } },
  visual = { a = { fg = "#F4ECE6", bg = "#531D5E", gui = "bold" }, b = { fg = "#3A2B2A", bg = "#DAD1CC" }, c = { fg = "#6C615F", bg = "#EADFD7" } },
  replace = { a = { fg = "#F4ECE6", bg = "#991727", gui = "bold" }, b = { fg = "#3A2B2A", bg = "#DAD1CC" }, c = { fg = "#6C615F", bg = "#EADFD7" } },
  command = { a = { fg = "#F4ECE6", bg = "#806102", gui = "bold" }, b = { fg = "#3A2B2A", bg = "#DAD1CC" }, c = { fg = "#6C615F", bg = "#EADFD7" } },
  terminal = { a = { fg = "#F4ECE6", bg = "#056258", gui = "bold" }, b = { fg = "#3A2B2A", bg = "#DAD1CC" }, c = { fg = "#6C615F", bg = "#EADFD7" } },
  inactive = { a = { fg = "#7A6D67", bg = "#EADFD7" }, b = { fg = "#7A6D67", bg = "#EADFD7" }, c = { fg = "#7A6D67", bg = "#EADFD7" } },
}
