-- Cocoa Rose Light for lualine (LazyVim's status line). Generated by tools/build.py; do not edit.
return {
  normal = { a = { fg = "#F4EBE7", bg = "#A34445", gui = "bold" }, b = { fg = "#3B2A2D", bg = "#DAD0CD" }, c = { fg = "#6E6161", bg = "#EADFDA" } },
  insert = { a = { fg = "#F4EBE7", bg = "#436517", gui = "bold" }, b = { fg = "#3B2A2D", bg = "#DAD0CD" }, c = { fg = "#6E6161", bg = "#EADFDA" } },
  visual = { a = { fg = "#F4EBE7", bg = "#5A1B5E", gui = "bold" }, b = { fg = "#3B2A2D", bg = "#DAD0CD" }, c = { fg = "#6E6161", bg = "#EADFDA" } },
  replace = { a = { fg = "#F4EBE7", bg = "#961227", gui = "bold" }, b = { fg = "#3B2A2D", bg = "#DAD0CD" }, c = { fg = "#6E6161", bg = "#EADFDA" } },
  command = { a = { fg = "#F4EBE7", bg = "#856102", gui = "bold" }, b = { fg = "#3B2A2D", bg = "#DAD0CD" }, c = { fg = "#6E6161", bg = "#EADFDA" } },
  terminal = { a = { fg = "#F4EBE7", bg = "#00625E", gui = "bold" }, b = { fg = "#3B2A2D", bg = "#DAD0CD" }, c = { fg = "#6E6161", bg = "#EADFDA" } },
  inactive = { a = { fg = "#7D6B6D", bg = "#EADFDA" }, b = { fg = "#7D6B6D", bg = "#EADFDA" }, c = { fg = "#7D6B6D", bg = "#EADFDA" } },
}
