-- Mocha Berry Light for lualine (LazyVim's status line). Generated by tools/build.py; do not edit.
return {
  normal = { a = { fg = "#F4E9EC", bg = "#9E4270", gui = "bold" }, b = { fg = "#3B2830", bg = "#DACED2" }, c = { fg = "#6D5F63", bg = "#EADCE0" } },
  insert = { a = { fg = "#F4E9EC", bg = "#3B671F", gui = "bold" }, b = { fg = "#3B2830", bg = "#DACED2" }, c = { fg = "#6D5F63", bg = "#EADCE0" } },
  visual = { a = { fg = "#F4E9EC", bg = "#4C1F67", gui = "bold" }, b = { fg = "#3B2830", bg = "#DACED2" }, c = { fg = "#6D5F63", bg = "#EADCE0" } },
  replace = { a = { fg = "#F4E9EC", bg = "#991629", gui = "bold" }, b = { fg = "#3B2830", bg = "#DACED2" }, c = { fg = "#6D5F63", bg = "#EADCE0" } },
  command = { a = { fg = "#F4E9EC", bg = "#806102", gui = "bold" }, b = { fg = "#3B2830", bg = "#DACED2" }, c = { fg = "#6D5F63", bg = "#EADCE0" } },
  terminal = { a = { fg = "#F4E9EC", bg = "#00625E", gui = "bold" }, b = { fg = "#3B2830", bg = "#DACED2" }, c = { fg = "#6D5F63", bg = "#EADCE0" } },
  inactive = { a = { fg = "#7C6A73", bg = "#EADCE0" }, b = { fg = "#7C6A73", bg = "#EADCE0" }, c = { fg = "#7C6A73", bg = "#EADCE0" } },
}
