-- Mocha Berry Dark for lualine (LazyVim's status line). Generated by tools/build.py; do not edit.
return {
  normal = { a = { fg = "#3A2830", bg = "#E78FB3", gui = "bold" }, b = { fg = "#F1E4E6", bg = "#544249" }, c = { fg = "#B1A2A6", bg = "#2D1D24" } },
  insert = { a = { fg = "#3A2830", bg = "#97C66E", gui = "bold" }, b = { fg = "#F1E4E6", bg = "#544249" }, c = { fg = "#B1A2A6", bg = "#2D1D24" } },
  visual = { a = { fg = "#3A2830", bg = "#BA94F1", gui = "bold" }, b = { fg = "#F1E4E6", bg = "#544249" }, c = { fg = "#B1A2A6", bg = "#2D1D24" } },
  replace = { a = { fg = "#3A2830", bg = "#F46E6B", gui = "bold" }, b = { fg = "#F1E4E6", bg = "#544249" }, c = { fg = "#B1A2A6", bg = "#2D1D24" } },
  command = { a = { fg = "#3A2830", bg = "#FBCF68", gui = "bold" }, b = { fg = "#F1E4E6", bg = "#544249" }, c = { fg = "#B1A2A6", bg = "#2D1D24" } },
  terminal = { a = { fg = "#3A2830", bg = "#4CD5C7", gui = "bold" }, b = { fg = "#F1E4E6", bg = "#544249" }, c = { fg = "#B1A2A6", bg = "#2D1D24" } },
  inactive = { a = { fg = "#A38B93", bg = "#2D1D24" }, b = { fg = "#A38B93", bg = "#2D1D24" }, c = { fg = "#A38B93", bg = "#2D1D24" } },
}
