-- Rosewood Light for lualine (LazyVim's status line). Generated by tools/build.py; do not edit.
return {
  normal = { a = { fg = "#F5E9E7", bg = "#A34249", gui = "bold" }, b = { fg = "#3D2629", bg = "#DBCECC" }, c = { fg = "#705F61", bg = "#EBDCDA" } },
  insert = { a = { fg = "#F5E9E7", bg = "#3E661D", gui = "bold" }, b = { fg = "#3D2629", bg = "#DBCECC" }, c = { fg = "#705F61", bg = "#EBDCDA" } },
  visual = { a = { fg = "#F5E9E7", bg = "#4E1F63", gui = "bold" }, b = { fg = "#3D2629", bg = "#DBCECC" }, c = { fg = "#705F61", bg = "#EBDCDA" } },
  replace = { a = { fg = "#F5E9E7", bg = "#961424", gui = "bold" }, b = { fg = "#3D2629", bg = "#DBCECC" }, c = { fg = "#705F61", bg = "#EBDCDA" } },
  command = { a = { fg = "#F5E9E7", bg = "#816103", gui = "bold" }, b = { fg = "#3D2629", bg = "#DBCECC" }, c = { fg = "#705F61", bg = "#EBDCDA" } },
  terminal = { a = { fg = "#F5E9E7", bg = "#00625B", gui = "bold" }, b = { fg = "#3D2629", bg = "#DBCECC" }, c = { fg = "#705F61", bg = "#EBDCDA" } },
  inactive = { a = { fg = "#7E6A6B", bg = "#EBDCDA" }, b = { fg = "#7E6A6B", bg = "#EBDCDA" }, c = { fg = "#7E6A6B", bg = "#EBDCDA" } },
}
