-- Rosewood Dark for lualine (LazyVim's status line). Generated by tools/build.py; do not edit.
return {
  normal = { a = { fg = "#3B2629", bg = "#E37B7C", gui = "bold" }, b = { fg = "#F2E4E2", bg = "#554143" }, c = { fg = "#B2A2A1", bg = "#2D1C1F" } },
  insert = { a = { fg = "#3B2629", bg = "#9DC56B", gui = "bold" }, b = { fg = "#F2E4E2", bg = "#554143" }, c = { fg = "#B2A2A1", bg = "#2D1C1F" } },
  visual = { a = { fg = "#3B2629", bg = "#D29CF1", gui = "bold" }, b = { fg = "#F2E4E2", bg = "#554143" }, c = { fg = "#B2A2A1", bg = "#2D1C1F" } },
  replace = { a = { fg = "#3B2629", bg = "#F37065", gui = "bold" }, b = { fg = "#F2E4E2", bg = "#554143" }, c = { fg = "#B2A2A1", bg = "#2D1C1F" } },
  command = { a = { fg = "#3B2629", bg = "#FECE69", gui = "bold" }, b = { fg = "#F2E4E2", bg = "#554143" }, c = { fg = "#B2A2A1", bg = "#2D1C1F" } },
  terminal = { a = { fg = "#3B2629", bg = "#56D5C0", gui = "bold" }, b = { fg = "#F2E4E2", bg = "#554143" }, c = { fg = "#B2A2A1", bg = "#2D1C1F" } },
  inactive = { a = { fg = "#A58A8C", bg = "#2D1C1F" }, b = { fg = "#A58A8C", bg = "#2D1C1F" }, c = { fg = "#A58A8C", bg = "#2D1C1F" } },
}
