# Chocolate Milk Light for PSReadLine (PowerShell typing colors). Generated by tools/build.py; do not edit.
# Dot-source it from $PROFILE:  . '<this repo>\ports\powershell\chocolate-milk-light.ps1'
# Needs PSReadLine 2.1+ (Windows PowerShell 5.1 and PowerShell 7 both work).
$e = [char]27
Set-PSReadLineOption -Colors @{
  Default = "$e[38;2;70;50;43m"
  Command = "$e[38;2;83;111;48m"
  Keyword = "$e[38;2;172;67;67m"
  String = "$e[38;2;83;111;48m"
  Number = "$e[38;2;135;82;138m"
  Type = "$e[38;2;123;100;21m"
  Operator = "$e[38;2;45;113;101m"
  Variable = "$e[38;2;44;74;115m"
  Member = "$e[38;2;70;50;43m"
  Parameter = "$e[38;2;44;74;115m"
  Comment = "$e[3;38;2;124;108;99m"
  ContinuationPrompt = "$e[38;2;124;108;99m"
  Emphasis = "$e[38;2;142;91;52m"
  Error = "$e[38;2;172;67;67m"
  Selection = "$e[48;2;227;214;204m"
  InlinePrediction = "$e[3;38;2;124;108;99m"
  ListPrediction = "$e[38;2;123;100;21m"
  ListPredictionSelected = "$e[48;2;227;214;204m"
  ListPredictionTooltip = "$e[38;2;124;108;99m"
}
