# Chocolate Milk Dark for PSReadLine (PowerShell typing colors). Generated by tools/build.py; do not edit.
# Dot-source it from $PROFILE:  . '<this repo>\ports\powershell\chocolate-milk-dark.ps1'
# Needs PSReadLine 2.1+ (Windows PowerShell 5.1 and PowerShell 7 both work).
$e = [char]27
Set-PSReadLineOption -Colors @{
  Default = "$e[38;2;242;231;222m"
  Command = "$e[38;2;176;202;133m"
  Keyword = "$e[38;2;244;136;125m"
  String = "$e[38;2;176;202;133m"
  Number = "$e[38;2;204;162;202m"
  Type = "$e[38;2;241;209;128m"
  Operator = "$e[38;2;144;200;176m"
  Variable = "$e[38;2;152;184;218m"
  Member = "$e[38;2;242;231;222m"
  Parameter = "$e[38;2;152;184;218m"
  Comment = "$e[3;38;2;179;160;151m"
  ContinuationPrompt = "$e[38;2;179;160;151m"
  Emphasis = "$e[38;2;224;168;110m"
  Error = "$e[38;2;244;136;125m"
  Selection = "$e[48;2;92;72;64m"
  InlinePrediction = "$e[3;38;2;179;160;151m"
  ListPrediction = "$e[38;2;241;209;128m"
  ListPredictionSelected = "$e[48;2;92;72;64m"
  ListPredictionTooltip = "$e[38;2;179;160;151m"
}
