# Cocoa Rose Dark for PSReadLine (PowerShell typing colors). Generated by tools/build.py; do not edit.
# Dot-source it from $PROFILE:  . '<this repo>\ports\powershell\cocoa-rose-dark.ps1'
# Needs PSReadLine 2.1+ (Windows PowerShell 5.1 and PowerShell 7 both work).
$e = [char]27
Set-PSReadLineOption -Colors @{
  Default = "$e[38;2;240;227;223m"
  Command = "$e[38;2;166;192;98m"
  Keyword = "$e[38;2;246;108;117m"
  String = "$e[38;2;166;192;98m"
  Number = "$e[38;2;224;147;225m"
  Type = "$e[38;2;250;203;98m"
  Operator = "$e[38;2;83;210;189m"
  Variable = "$e[38;2;89;165;239m"
  Member = "$e[38;2;240;227;223m"
  Parameter = "$e[38;2;89;165;239m"
  Comment = "$e[3;38;2;160;138;138m"
  ContinuationPrompt = "$e[38;2;160;138;138m"
  Emphasis = "$e[38;2;237;136;136m"
  Error = "$e[38;2;246;108;117m"
  Selection = "$e[48;2;78;58;62m"
  InlinePrediction = "$e[3;38;2;160;138;138m"
  ListPrediction = "$e[38;2;250;203;98m"
  ListPredictionSelected = "$e[48;2;78;58;62m"
  ListPredictionTooltip = "$e[38;2;160;138;138m"
}
