# Cocoa Copper Light for PSReadLine (PowerShell typing colors). Generated by tools/build.py; do not edit.
# Dot-source it from $PROFILE:  . '<this repo>\ports\powershell\cocoa-copper-light.ps1'
# Needs PSReadLine 2.1+ (Windows PowerShell 5.1 and PowerShell 7 both work).
$e = [char]27
Set-PSReadLineOption -Colors @{
  Default = "$e[38;2;58;43;42m"
  Command = "$e[38;2;71;101;23m"
  Keyword = "$e[38;2;153;23;39m"
  String = "$e[38;2;71;101;23m"
  Number = "$e[38;2;83;29;94m"
  Type = "$e[38;2;128;97;2m"
  Operator = "$e[38;2;5;98;88m"
  Variable = "$e[38;2;0;73;124m"
  Member = "$e[38;2;58;43;42m"
  Parameter = "$e[38;2;0;73;124m"
  Comment = "$e[3;38;2;122;109;103m"
  ContinuationPrompt = "$e[38;2;122;109;103m"
  Emphasis = "$e[38;2;137;43;50m"
  Error = "$e[38;2;153;23;39m"
  Selection = "$e[48;2;229;213;203m"
  InlinePrediction = "$e[3;38;2;122;109;103m"
  ListPrediction = "$e[38;2;128;97;2m"
  ListPredictionSelected = "$e[48;2;229;213;203m"
  ListPredictionTooltip = "$e[38;2;122;109;103m"
}
