# Cocoa Rose Light for PSReadLine (PowerShell typing colors). Generated by tools/build.py; do not edit.
# Dot-source it from $PROFILE:  . '<this repo>\ports\powershell\cocoa-rose-light.ps1'
# Needs PSReadLine 2.1+ (Windows PowerShell 5.1 and PowerShell 7 both work).
$e = [char]27
Set-PSReadLineOption -Colors @{
  Default = "$e[38;2;59;42;45m"
  Command = "$e[38;2;67;101;23m"
  Keyword = "$e[38;2;150;18;39m"
  String = "$e[38;2;67;101;23m"
  Number = "$e[38;2;90;27;94m"
  Type = "$e[38;2;133;97;2m"
  Operator = "$e[38;2;0;98;94m"
  Variable = "$e[38;2;0;68;134m"
  Member = "$e[38;2;59;42;45m"
  Parameter = "$e[38;2;0;68;134m"
  Comment = "$e[3;38;2;125;107;109m"
  ContinuationPrompt = "$e[38;2;125;107;109m"
  Emphasis = "$e[38;2;163;68;69m"
  Error = "$e[38;2;150;18;39m"
  Selection = "$e[48;2;230;211;205m"
  InlinePrediction = "$e[3;38;2;125;107;109m"
  ListPrediction = "$e[38;2;133;97;2m"
  ListPredictionSelected = "$e[48;2;230;211;205m"
  ListPredictionTooltip = "$e[38;2;125;107;109m"
}
