# Cocoa Copper Dark for PSReadLine (PowerShell typing colors). Generated by tools/build.py; do not edit.
# Dot-source it from $PROFILE:  . '<this repo>\ports\powershell\cocoa-copper-dark.ps1'
# Needs PSReadLine 2.1+ (Windows PowerShell 5.1 and PowerShell 7 both work).
$e = [char]27
Set-PSReadLineOption -Colors @{
  Default = "$e[38;2;241;229;222m"
  Command = "$e[38;2;163;193;100m"
  Keyword = "$e[38;2;244;111;104m"
  String = "$e[38;2;163;193;100m"
  Number = "$e[38;2;215;154;238m"
  Type = "$e[38;2;254;206;105m"
  Operator = "$e[38;2;90;210;184m"
  Variable = "$e[38;2;54;169;237m"
  Member = "$e[38;2;241;229;222m"
  Parameter = "$e[38;2;54;169;237m"
  Comment = "$e[3;38;2;163;144;136m"
  ContinuationPrompt = "$e[38;2;163;144;136m"
  Emphasis = "$e[38;2;229;128;118m"
  Error = "$e[38;2;244;111;104m"
  Selection = "$e[48;2;76;58;56m"
  InlinePrediction = "$e[3;38;2;163;144;136m"
  ListPrediction = "$e[38;2;254;206;105m"
  ListPredictionSelected = "$e[48;2;76;58;56m"
  ListPredictionTooltip = "$e[38;2;163;144;136m"
}
