# Mocha Berry Dark for PSReadLine (PowerShell typing colors). Generated by tools/build.py; do not edit.
# Dot-source it from $PROFILE:  . '<this repo>\ports\powershell\mocha-berry-dark.ps1'
# Needs PSReadLine 2.1+ (Windows PowerShell 5.1 and PowerShell 7 both work).
$e = [char]27
Set-PSReadLineOption -Colors @{
  Default = "$e[38;2;241;228;230m"
  Command = "$e[38;2;151;198;110m"
  Keyword = "$e[38;2;244;110;107m"
  String = "$e[38;2;151;198;110m"
  Number = "$e[38;2;186;148;241m"
  Type = "$e[38;2;251;207;104m"
  Operator = "$e[38;2;76;213;199m"
  Variable = "$e[38;2;94;164;239m"
  Member = "$e[38;2;241;228;230m"
  Parameter = "$e[38;2;94;164;239m"
  Comment = "$e[3;38;2;163;139;147m"
  ContinuationPrompt = "$e[38;2;163;139;147m"
  Emphasis = "$e[38;2;231;143;179m"
  Error = "$e[38;2;244;110;107m"
  Selection = "$e[48;2;79;57;67m"
  InlinePrediction = "$e[3;38;2;163;139;147m"
  ListPrediction = "$e[38;2;251;207;104m"
  ListPredictionSelected = "$e[48;2;79;57;67m"
  ListPredictionTooltip = "$e[38;2;163;139;147m"
}
