# Mocha Berry Light for PSReadLine (PowerShell typing colors). Generated by tools/build.py; do not edit.
# Dot-source it from $PROFILE:  . '<this repo>\ports\powershell\mocha-berry-light.ps1'
# Needs PSReadLine 2.1+ (Windows PowerShell 5.1 and PowerShell 7 both work).
$e = [char]27
Set-PSReadLineOption -Colors @{
  Default = "$e[38;2;59;40;48m"
  Command = "$e[38;2;59;103;31m"
  Keyword = "$e[38;2;153;22;41m"
  String = "$e[38;2;59;103;31m"
  Number = "$e[38;2;76;31;103m"
  Type = "$e[38;2;128;97;2m"
  Operator = "$e[38;2;0;98;94m"
  Variable = "$e[38;2;0;72;132m"
  Member = "$e[38;2;59;40;48m"
  Parameter = "$e[38;2;0;72;132m"
  Comment = "$e[3;38;2;124;106;115m"
  ContinuationPrompt = "$e[38;2;124;106;115m"
  Emphasis = "$e[38;2;158;66;112m"
  Error = "$e[38;2;153;22;41m"
  Selection = "$e[48;2;230;208;216m"
  InlinePrediction = "$e[3;38;2;124;106;115m"
  ListPrediction = "$e[38;2;128;97;2m"
  ListPredictionSelected = "$e[48;2;230;208;216m"
  ListPredictionTooltip = "$e[38;2;124;106;115m"
}
