# Rosewood Light for PSReadLine (PowerShell typing colors). Generated by tools/build.py; do not edit.
# Dot-source it from $PROFILE:  . '<this repo>\ports\powershell\rosewood-light.ps1'
# Needs PSReadLine 2.1+ (Windows PowerShell 5.1 and PowerShell 7 both work).
$e = [char]27
Set-PSReadLineOption -Colors @{
  Default = "$e[38;2;61;38;41m"
  Command = "$e[38;2;62;102;29m"
  Keyword = "$e[38;2;150;20;36m"
  String = "$e[38;2;62;102;29m"
  Number = "$e[38;2;78;31;99m"
  Type = "$e[38;2;129;97;3m"
  Operator = "$e[38;2;0;98;91m"
  Variable = "$e[38;2;0;72;132m"
  Member = "$e[38;2;61;38;41m"
  Parameter = "$e[38;2;0;72;132m"
  Comment = "$e[3;38;2;126;106;107m"
  ContinuationPrompt = "$e[38;2;126;106;107m"
  Emphasis = "$e[38;2;163;66;73m"
  Error = "$e[38;2;150;20;36m"
  Selection = "$e[48;2;232;210;208m"
  InlinePrediction = "$e[3;38;2;126;106;107m"
  ListPrediction = "$e[38;2;129;97;3m"
  ListPredictionSelected = "$e[48;2;232;210;208m"
  ListPredictionTooltip = "$e[38;2;126;106;107m"
}
