# Rosewood Dark for PSReadLine (PowerShell typing colors). Generated by tools/build.py; do not edit.
# Dot-source it from $PROFILE:  . '<this repo>\ports\powershell\rosewood-dark.ps1'
# Needs PSReadLine 2.1+ (Windows PowerShell 5.1 and PowerShell 7 both work).
$e = [char]27
Set-PSReadLineOption -Colors @{
  Default = "$e[38;2;242;228;226m"
  Command = "$e[38;2;157;197;107m"
  Keyword = "$e[38;2;243;112;101m"
  String = "$e[38;2;157;197;107m"
  Number = "$e[38;2;210;156;241m"
  Type = "$e[38;2;254;206;105m"
  Operator = "$e[38;2;86;213;192m"
  Variable = "$e[38;2;76;167;238m"
  Member = "$e[38;2;242;228;226m"
  Parameter = "$e[38;2;76;167;238m"
  Comment = "$e[3;38;2;165;138;140m"
  ContinuationPrompt = "$e[38;2;165;138;140m"
  Emphasis = "$e[38;2;227;123;124m"
  Error = "$e[38;2;243;112;101m"
  Selection = "$e[48;2;80;53;57m"
  InlinePrediction = "$e[3;38;2;165;138;140m"
  ListPrediction = "$e[38;2;254;206;105m"
  ListPredictionSelected = "$e[48;2;80;53;57m"
  ListPredictionTooltip = "$e[38;2;165;138;140m"
}
